
DEAL::Construct A
DEAL::Construct B
DEAL::a mutable
DEAL::b const
DEAL::r mutable
DEAL::s const
DEAL::t mutable
DEAL::u const
DEAL::Construct C
DEAL::Construct D
DEAL::Destruct D
--------------------------------------------------------
An error occurred in file <source/subscriptor.cc> in function
    Subscriptor::~Subscriptor()
The violated condition was: 
    counter == 0
The name and call sequence of the exception was:
    ExcInUse(counter, object_info->name())
Additional Information: 
Object of class 4Test is still used by 1 other objects.
--------------------------------------------------------
DEAL::Destruct C
DEAL::Destruct B
DEAL::Destruct A
